trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - 'v*'

strategy:
  matrix:
{% for os, architectures in [('MacOs', ['x64']), ('Ubuntu', ['x64']), ('Windows', ['x86', 'x64'])] %}
{% for minor in range(min_python_version.split(".")[1]|int, (max_python_version.split(".")[1])|int + 1) %}
{% for architecture in architectures %}
    {{os}} CPython3.{{minor}}{{" (%s)" % architecture if architectures|length > 1 else ""}}:
      image: '{{os|lower}}-latest'
      python.version: '3.{{minor}}'
      python.architecture: '{{architecture}}'
{% endfor %}
{% endfor %}
    {{os}} PyPy3:
      image: '{{os|lower}}-latest'
      python.version: 'pypy3'
      python.architecture: '{{architectures[0]}}'
{% endfor %}

pool:
  vmImage: $(image)

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: '$(python.architecture)'
  - script: python -m pip install --upgrade pip setuptools
    displayName: 'Install packaging tools'
  - script: python -m pip install --force-reinstall -r requirements-tests.txt
    displayName: 'Install tests dependencies'
  - script: python setup.py develop
    displayName: 'Install in editable mode'
    env:
      CXXFLAGS: --coverage -O0
  - script: pytest
    displayName: 'Run tests'
  - script: python -m doctest README.md
    displayName: 'Run doctests'
  - script: python -m pip install --upgrade codecov gcovr
    condition: succeeded()
    displayName: 'Install coverage dependencies'
  - script: gcovr --filter src/ --filter include/ --xml -o coverage_cpp.xml
    condition: succeeded()
    displayName: 'Collect C++ coverage'
  - script: python -m codecov -f coverage.xml -X gcov
    condition: succeeded()
    displayName: 'Upload coverage'
    env:
      CODECOV_TOKEN: $(CODECOV_TOKEN)
  - script: python -m codecov -f coverage_cpp.xml -X gcov
    condition: succeeded()
    displayName: 'Upload C++ coverage'
    env:
      CODECOV_TOKEN: $(CODECOV_TOKEN)
  - script: python -m pip install --upgrade cibuildwheel
    condition: and(succeeded(), startsWith(variables['python.version'], '3.'), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    displayName: 'Install build requirements'
  - bash:
      CIBW_BUILD=$(python -c 'import sys; print("cp" + "".join(map(str, sys.version_info[:2])) + "-*")')
      cibuildwheel --output-dir dist
    condition: and(succeeded(), startsWith(variables['python.version'], '3.'), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    displayName: 'Build wheels'
  - script: python -m pip install --upgrade twine
    condition: and(succeeded(), startsWith(variables['python.version'], '3.'), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    displayName: 'Install deployment requirements'
  - script: twine upload --skip-existing dist/*
    condition: and(succeeded(), startsWith(variables['python.version'], '3.'), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    displayName: 'Deploy wheels'
    env:
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: $(TWINE_PASSWORD)
