version: '3'

services:
  {{project}}-cpython:
    build:
      context: .
      args:
        - IMAGE_NAME=${CPYTHON_IMAGE_NAME}
        - IMAGE_VERSION=${CPYTHON_IMAGE_VERSION}
    image: {{dockerhub_login}}/{{project}}-cpython:{{version}}
    volumes:
      - ./{{project}}/:/opt/{{project}}/{{project}}/
      - ./pytest.ini:/opt/{{project}}/pytest.ini
      - ./README.md:/opt/{{project}}/README.md
      - ./requirements-setup.txt:/opt/{{project}}/requirements-setup.txt
      - ./requirements-tests.txt:/opt/{{project}}/requirements-tests.txt
      - ./requirements.txt:/opt/{{project}}/requirements.txt
      - ./setup.py:/opt/{{project}}/setup.py
      - ./src/:/opt/{{project}}/src/
      - ./tests/:/opt/{{project}}/tests/
    entrypoint: pytest
